### PR TITLE
Merge all commands in main script

### PR DESCRIPTION
**Pull request by eplanet**
This is a complete rewrite of the way it works from now, but I think it's a lot clearer to use with only one entry point: `glacier.py`.

The idea is simple: make use of the Python argparse subparsers so that only one script contains all the relevant commands.

### CODE REVIEW

**Comment by eplanet** [comment]
I suppose if you're willing to merge that I should rebase from your latest changes. Could you confirm it's worth it though?

**Comment by tbumi** [comment]
Oh, sorry about the late reply. I was going to tell you, I restructured the code to use [click](http://click.pocoo.org/6/). It is worth a look again to see if the changes in this PR are still relevant.

**Comment by eplanet** [comment]
No problem, that's your project! What I liked though, is the very few dependencies `glacier-upload` had. So now I see it takes a different direction and includes quite a few dependencies... But that's for you to decide.

I think however it is still relevant merging the different commands in one unique script that rules them all. See for instance the similar project: [basak/glacier-cli](https://github.com/basak/glacier-cli) (that by the way has now fewer dependencies than `glacier-upload`).

**Comment by eplanet** [comment]
Apparently you don't want that PR so I'm closing it.

**Pull request closed without merging**
